name: Seattle Conlang Club

domain: conlang.club
url: https://conlang.club
baseurl: ""

collections:
    sign-ling:
        output: true
        order:
            - index.html
            - phonology/sign-constituents.html
            - links.html

plugins:
    - jekyll-postcss

postcss:
    cache: false