name: Seattle Conlang Club

domain: conlang.club
url: https://conlang.club
baseurl: ""

collections:
    crossword:
        output: true
    pidgin:
        output: true

plugins:
    - jekyll-postcss

postcss:
    cache: false